In [24]:
import numpy as np
import jax.numpy as jnp
from manifpy import SE3, SE3Tangent, SO3, SO3Tangent

In [23]:
X = SE3.Random()
print("x is \n", x, "\n"
      "x is ",X.x(),
      "\ny is ", X.y(),
      "\nz is ", X.z(),
      "\ntranslation is ", X.translation(),
      "\ntransformation is \n", X.transform(),
      "\nrotation is \n", X.rotation(),
      "\nadjoint is \n", X.adj(),
      "\nLie Algebra is \n", X.log())

x is 
 -0.466669 0.0795207 -0.249586  0.176643  -2.73933 0.0688413 
x is  -0.29190264050471715 
y is  0.3757227805330059 
z is  -0.6680516673568877 
translation is  [-0.29190264  0.37572278 -0.66805167] 
transformation is 
 [[ 0.43141319 -0.52362709  0.73464095 -0.29190264]
 [ 0.62368405  0.76148747  0.1765079   0.37572278]
 [-0.6518442   0.38203601  0.6550936  -0.66805167]
 [ 0.          0.          0.          1.        ]] 
rotation is 
 [[ 0.43141319 -0.52362709  0.73464095]
 [ 0.62368405  0.76148747  0.1765079 ]
 [-0.6518442   0.38203601  0.6550936 ]] 
adjoint is 
 [[ 0.43141319 -0.52362709  0.73464095  0.17174046  0.6522526   0.36404999]
 [ 0.62368405  0.76148747  0.1765079  -0.47848135  0.46132727 -0.29955456]
 [-0.6518442   0.38203601  0.6550936  -0.34414679 -0.02554158 -0.32754446]
 [ 0.          0.          0.          0.43141319 -0.52362709  0.73464095]
 [ 0.          0.          0.          0.62368405  0.76148747  0.1765079 ]
 [ 0.          0.          0.         -0.6518442 

In [21]:
x = SE3Tangent.Random()
print("x is \n", x, "\n",
      "x hat is \n", x.hat(),
      "\nexp(x)  is \n", x.exp().transform(),
      "\nadjoint x on Lie Algebra is \n", x.smallAdj()
      )

x is 
 -0.466669 0.0795207 -0.249586  0.176643  -2.73933 0.0688413 
x hat is 
 [[ 0.         -0.06884131 -2.73933129 -0.4666685 ]
 [ 0.06884131  0.         -0.17664267  0.07952068]
 [ 2.73933129  0.17664267  0.         -0.24958605]
 [ 0.          0.          0.          0.        ]] 
exp(x)  is 
 [[-0.91476665 -0.13305745 -0.3814416   0.10104896]
 [-0.1137298   0.99083459 -0.07288584  0.1133561 ]
 [ 0.38764353 -0.02329226 -0.92151504 -0.35993695]
 [ 0.          0.          0.          1.        ]] 
adjoint x on Lie Algebra is 
 [[ 0.         -0.06884131 -2.73933129  0.          0.24958605  0.07952068]
 [ 0.06884131  0.         -0.17664267 -0.24958605  0.          0.4666685 ]
 [ 2.73933129  0.17664267  0.         -0.07952068 -0.4666685   0.        ]
 [ 0.          0.          0.          0.         -0.06884131 -2.73933129]
 [ 0.          0.          0.          0.06884131  0.         -0.17664267]
 [ 0.          0.          0.          2.73933129  0.17664267  0.        ]]


In [36]:
print(x.exp().adj())

[[ 0.68552941  0.61770753  0.38533989  0.42463356 -0.75351631  0.45246784]
 [-0.69555607  0.7120268   0.09601868  0.47768089  0.38951239  0.571874  ]
 [-0.21506087 -0.33384913  0.91776554 -0.19136465 -0.56345645 -0.24980726]
 [ 0.          0.          0.          0.68552941  0.61770753  0.38533989]
 [ 0.          0.          0.         -0.69555607  0.7120268   0.09601868]
 [ 0.          0.          0.         -0.21506087 -0.33384913  0.91776554]]


In [42]:
type(x.exp())

manifpy._bindings.SE3

In [29]:
x = SO3Tangent.Random()
print("\nx is \n", x,
      "\nx hat is \n", x.hat(),
      "\nexp(x)  is \n", x.exp().rotation(),
      "\nthe 1st generator/basis is \n", x.generator(2),
      "\nadjoint x on Lie Group is \n", x.exp().adj(),
      "\nadjoint x on Lie Algebra is \n", x.smallAdj(),
      )


x is 
 -1.13812 0.454259   1.9602 
x hat is 
 [[ 0.         -1.96020373  0.45425941]
 [ 1.96020373  0.          1.13812369]
 [-0.45425941 -1.13812369  0.        ]] 
exp(x)  is 
 [[-0.26898485 -0.78768752 -0.55425221]
 [ 0.4636026  -0.61029793  0.64234654]
 [-0.84422733 -0.08417128  0.52933488]] 
the 1st generator/basis is 
 [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]] 
adjoint x on Lie Group is 
 [[-0.26898485 -0.78768752 -0.55425221]
 [ 0.4636026  -0.61029793  0.64234654]
 [-0.84422733 -0.08417128  0.52933488]] 
adjoint x on Lie Algebra is 
 [[ 0.         -1.96020373  0.45425941]
 [ 1.96020373  0.          1.13812369]
 [-0.45425941 -1.13812369  0.        ]]


In [11]:
type(x.hat())

numpy.ndarray