In [2]:
import numpy as np
import jax.numpy as jnp
from manifpy import SE3, SE3Tangent, SO3Tangent

In [2]:
X = SE3.Random()
print("x is \n", X, "\n"
      "x is ",X.x(),
      "\ny is ", X.y(),
      "\nz is ", X.z(),
      "\ntranslation is ", X.translation(),
      "\ntransformation is \n", X.transform(),
      "\nrotation is \n", X.rotation(),
      "\nadjoint is \n", X.adj(),
      "\nLie Algebra is \n", X.log(),
      "\ntype of X is:", type(X))

x is 
 0.0268018  0.904459   0.83239 -0.498594  0.518899 -0.456224 -0.523457 
x is  0.026801820391231024 
y is  0.9044594503494257 
z is  0.8323901360074013 
translation is  [0.02680182 0.90445945 0.83239014] 
transformation is 
 [[ 0.0452059  -0.99506743 -0.08830191  0.02680182]
 [-0.03981301  0.08652748 -0.99545362  0.90445945]
 [ 0.99818403  0.04851594 -0.03570508  0.83239014]
 [ 0.          0.          0.          1.        ]] 
rotation is 
 [[ 0.0452059  -0.99506743 -0.08830191]
 [-0.03981301  0.08652748 -0.99545362]
 [ 0.99818403  0.04851594 -0.03570508]] 
adjoint is 
 [[ 0.0452059  -0.99506743 -0.08830191  0.93595693 -0.02814392  0.79631198]
 [-0.03981301  0.08652748 -0.99545362  0.01087579 -0.82958463 -0.07254468]
 [ 0.99818403  0.04851594 -0.03570508 -0.04195396  0.90231724  0.05318553]
 [ 0.          0.          0.          0.0452059  -0.99506743 -0.08830191]
 [ 0.          0.          0.         -0.03981301  0.08652748 -0.99545362]
 [ 0.          0.          0.          0.99

In [9]:
from jax.scipy.linalg import expm

x = SE3Tangent.Random()
Q = np.eye(6)

print("x is \n", x, "\n",
      "\nx.coeffs() is \n", x.coeffs(),
      "\nx hat is \n", x.hat(),
      "\ntype of x hat is \n", type(x.hat()),
      "\nexp(x)  is \n", x.exp().transform(),
      "\nadjoint x on Lie Algebra is \n", x.smallAdj(),
      "\nx.T @ Q @ x is \n", x.coeffs().T @ Q @ x.coeffs(),
      "\njax expm of x is\n", expm(x.hat())
      )

x is 
  0.271423  0.434594 -0.716795 -0.388453 -0.309087  -1.89623 
 
x.coeffs() is 
 [ 0.27142346  0.43459386 -0.71679489 -0.38845297 -0.30908682 -1.89622585] 
x hat is 
 [[ 0.          1.89622585 -0.30908682  0.27142346]
 [-1.89622585  0.          0.38845297  0.43459386]
 [ 0.30908682 -0.38845297  0.         -0.71679489]
 [ 0.          0.          0.          0.        ]] 
type of x hat is 
 <class 'numpy.ndarray'> 
exp(x)  is 
 [[-0.32538885  0.93811304  0.11860025  0.44380343]
 [-0.85188991 -0.34526714  0.3937946  -0.12720936]
 [ 0.41037262  0.02710202  0.91151511 -0.66053342]
 [ 0.          0.          0.          1.        ]] 
adjoint x on Lie Algebra is 
 [[ 0.          1.89622585 -0.30908682  0.          0.71679489  0.43459386]
 [-1.89622585  0.          0.38845297 -0.71679489  0.         -0.27142346]
 [ 0.30908682 -0.38845297  0.         -0.43459386  0.27142346  0.        ]
 [ 0.          0.          0.          0.          1.89622585 -0.30908682]
 [ 0.          0.          0.

In [65]:
from traoptlibrary.traopt_utilis import SE32manifSE3
import numpy as np
from manifpy import SE3

print(np.array([SE32manifSE3(np.identity(4)) for i in range(10)]))
print([SE32manifSE3(np.identity(4)) for i in range(10)])

[<manifpy._bindings.SE3 object at 0x7f67f869dc30>, <manifpy._bindings.SE3 object at 0x7f67bba6f330>, <manifpy._bindings.SE3 object at 0x7f67bba1d8b0>, <manifpy._bindings.SE3 object at 0x7f67bb95af70>, <manifpy._bindings.SE3 object at 0x7f67bb463930>, <manifpy._bindings.SE3 object at 0x7f67bb482a30>, <manifpy._bindings.SE3 object at 0x7f67bb96e2b0>, <manifpy._bindings.SE3 object at 0x7f67bb937530>, <manifpy._bindings.SE3 object at 0x7f67bb92a7b0>, <manifpy._bindings.SE3 object at 0x7f67bb4fbe70>]


In [ ]:
x = SO3Tangent.Random()
print("\nx is \n", x,
      "\nx hat is \n", x.hat(),
      "\nexp(x)  is \n", x.exp().rotation(),
      "\nthe 1st generator/basis is \n", x.generator(2),
      "\nadjoint x on Lie Group is \n", x.exp().adj(),
      "\nadjoint x on Lie Algebra is \n", x.smallAdj(),
      "\ntype of x is",type(x.hat())
      )


x is 
 -0.913837  0.248753  -1.70188 
x hat is 
 [[ 0.          1.7018785   0.24875285]
 [-1.7018785   0.          0.91383675]
 [-0.24875285 -0.91383675  0.        ]] 
exp(x)  is 
 [[-0.06684132  0.73051023  0.67962273]
 [-0.89446684 -0.34568777  0.28360015]
 [ 0.44211007 -0.58894378  0.6765234 ]] 
the 1st generator/basis is 
 [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]] 
adjoint x on Lie Group is 
 [[-0.06684132  0.73051023  0.67962273]
 [-0.89446684 -0.34568777  0.28360015]
 [ 0.44211007 -0.58894378  0.6765234 ]] 
adjoint x on Lie Algebra is 
 [[ 0.          1.7018785   0.24875285]
 [-1.7018785   0.          0.91383675]
 [-0.24875285 -0.91383675  0.        ]] 
type of x is <class 'numpy.ndarray'>


**Show Lie group composite operation doesn't commute.**

In [ ]:
X1 = SE3.Random()
X2 = SE3.Random()

print("\nLog( X1^{-1} X2 ) is\n", (X1.inverse() * X2).log(),
      "\nLog( X2 X1^{-1} ) is\n", (X2 * X1.inverse()).log(),
      )



Log( X1^{-1} X2 ) is
   1.52959 -0.732515 -0.424628 -0.372802   1.60682 0.0209665 
Log( X2 X1^{-1} ) is
  0.342474   1.13539 0.0241945   -1.0893  -1.21279 -0.252694


In [ ]:
X = SE3.Random()
J = np.empty((SE3.DoF, SE3.DoF))
X.log(J)
J

array([[ 0.88543078, -0.06131578, -0.58325924, -0.1238093 ,  0.02090976,
        -0.3167931 ],
       [-0.21038934,  0.83415273, -0.66717766, -0.21651191, -0.0712733 ,
        -0.09076124],
       [ 0.54743702,  0.69687164,  0.72349844,  0.25197164,  0.15409978,
        -0.1824661 ],
       [ 0.        ,  0.        ,  0.        ,  0.88543078, -0.06131578,
        -0.58325924],
       [ 0.        ,  0.        ,  0.        , -0.21038934,  0.83415273,
        -0.66717766],
       [ 0.        ,  0.        ,  0.        ,  0.54743702,  0.69687164,
         0.72349844]])

**Compare manif and jax autodiff Jacobian matrix**

In [19]:
import jax.scipy.linalg as jsl
from traoptlibrary.traopt_utilis import quatpos2SE3, se3_vee, se3_hat
import scipy.linalg as sl
import jax
from manifpy import SE3Tangent

quat0 = np.array([1, 0, 0, 0])
p0 = np.array([0, 0, 3])

X0 = quatpos2SE3( np.concatenate((quat0, p0)) )
print(X0)

x0 = se3_vee(sl.logm( X0 ))
print(x0)

dexp_jax = jax.jacfwd(jsl.expm)
J_jax = dexp_jax(se3_hat(x0))

x0_mnf = SE3Tangent(x0)
J_mnf = np.empty((SE3.DoF,SE3.DoF))
x0_mnf.exp( J_mnf )

print(  "\nFor expm map,\n", 
        "\nShape of manif Jacobian\n", J_mnf.shape, 
        "\nType of manif Jacobian\n", type(J_mnf), 
        "\nManif Jacobian is\n", J_mnf,
        "\nShape of jax Jacobian\n", J_jax.shape, 
        "\nJax Jacobian is\n", J_jax,
        "\nTensor inverse of jax Jacobian is\n", np.linalg.tensorinv(J_jax),
    )

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]
[0. 0. 0. 0. 0. 3.]

For expm map,
 
Shape of manif Jacobian
 (6, 6) 
Type of manif Jacobian
 <class 'numpy.ndarray'> 
Manif Jacobian is
 [[ 0.04704     0.66333083  0.          0.          0.          0.        ]
 [-0.66333083  0.04704     0.          0.          0.          0.        ]
 [ 0.          0.          1.          0.          0.          0.        ]
 [ 0.          0.          0.          0.04704     0.66333083  0.        ]
 [ 0.          0.          0.         -0.66333083  0.04704     0.        ]
 [ 0.          0.          0.          0.          0.          1.        ]] 
Shape of jax Jacobian
 (4, 4, 4, 4) 
Jax Jacobian is
 [[[[1.  0.  0.  0. ]
   [0.  0.  0.  0. ]
   [0.  0.  0.  0. ]
   [0.  0.  0.  0. ]]

  [[0.  1.  0.  0. ]
   [0.  0.  0.  0. ]
   [0.  0.  0.  0. ]
   [0.  0.  0.  0. ]]

  [[0.  0.  1.  0. ]
   [0.  0.  0.  0. ]
   [0.  0.  0.  0. ]
   [0.  0.  0.  0. ]]

  [[0.  0.  1.5 1. ]
   [0.  0.  0.  

**show manif can't be jit**

In [10]:
import jax

def gminus(x1,x2):
    # return x1.rminus( x2 ) 
    return x1 - x2 

gminus_jit = jax.jit(gminus)

x1 = SE3.Random()
x2 = SE3.Random()

gminus_jit(x1, x2)

TypeError: Cannot interpret value of type <class 'manifpy._bindings.SE3'> as an abstract array; it does not have a dtype attribute

**Test the manif jacobian, and show its organization of tangent vector [v,w] instead of [w,v]**

In [64]:
a = SE3Tangent([1,2,3,4,5,6])
a.hat()

a = SE3Tangent([0,0,1,0,0,0])
da = np.array([ 0,0,0.001,0.001,0,0 ])
# da = np.array([ -0.01, 0., 0., 0., 0.01, 0. ])
a2 = SE3Tangent(a.coeffs() + da)

A = SE3.Identity()
J1 = np.empty((6,6))
J2 = np.empty((6,6))
B = A.rplus( a, J1, J2 )
print(J2)
print(B.log())

B2 = A.rplus( a2, J )
print(B2 - B)


[[ 1.   0.   0.   0.   0.5  0. ]
 [ 0.   1.   0.  -0.5  0.   0. ]
 [ 0.   0.   1.   0.   0.   0. ]
 [ 0.   0.   0.   1.   0.   0. ]
 [ 0.   0.   0.   0.   1.   0. ]
 [ 0.   0.   0.   0.   0.   1. ]]
0 0 1 0 0 0
         0    -0.0005 0.00100008      0.001          0          0


In [11]:
from traoptlibrary.traopt_utilis import se3_vee
from scipy.linalg import logm

X1 = SE3.Random()
X2 = SE3.Random()

Y1 = X1.transform()
Y2 = X2.transform()

print("\nmanif Log result is\n", X1 - X2,
      "\nnumerical result is\n", se3_vee(logm(np.linalg.inv( Y2 ) @ Y1)))


manif Log result is
   1.15939 0.0602331  0.147916  -1.56223   0.74203  0.817822 
numerical result is
 [-1.5622338   0.7420303   0.81782216  1.1593918   0.06023308  0.14791594]


In [19]:
q_ref = SE3.Random()
q = SE3.Random()

q_err = q.rminus( q_ref ).coeffs()

q_err = se3_vee(logm(np.linalg.inv( q_ref.transform() ) @ q.transform() ))

In [82]:
%time
q_ref = SE3.Random()
q = SE3.Random()
a = [ q.rminus( q_ref ).coeffs() for i in range(100) ]

# q_err = q.rminus( q_ref ).coeffs()

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.48 µs


In [87]:
%time
a = [ se3_vee(logm(np.linalg.inv( q_ref.transform() ) @ q.transform() )) for i in range(100) ]

# q_err = se3_vee(logm(np.linalg.inv( q_ref.transform() ) @ q.transform() ))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.48 µs


In [78]:
import manifpy
type(a) == SE3Tangent

True

In [90]:
from traoptlibrary.traopt_utilis import se3_vee, se3_hat

a = np.random.rand(6,1)
h = 0.1
print(se3_hat( a ) * h)
print(se3_hat( a * h ) )

[[ 0.         -0.07320058  0.0954188   0.08211882]
 [ 0.07320058  0.         -0.04568241  0.05043102]
 [-0.0954188   0.04568241  0.          0.01670882]
 [ 0.          0.          0.          0.        ]]
[[ 0.         -0.07320058  0.0954188   0.08211882]
 [ 0.07320058  0.         -0.04568241  0.05043102]
 [-0.0954188   0.04568241  0.          0.01670882]
 [ 0.          0.          0.          0.        ]]


In [92]:
x = SE3Tangent.Random()
print(x)
print(x * 3)

 0.666477  0.850753  0.746543   0.39385 -0.705477   2.72937
 1.99943  2.55226  2.23963  1.18155 -2.11643  8.18812


In [13]:
from traoptlibrary.traopt_utilis import SE32manifSE3, manifse32se3, se3_vee
from scipy.linalg import logm

q_new = SE3.Random().transform()
q = SE3.Random().transform()

print("q_new is \n", q_new,
      "\nq is \n", q)

q_new_mnf = SE32manifSE3(q_new)
q_mnf = SE32manifSE3(q)

print("q_new_mnf is \n", q_new_mnf.transform(),
      "\nq_mnf is \n", q_mnf.transform())

print("se3_vee(logm(np.linalg.inv( q ) @ q_new )) is\n", se3_vee(logm(np.linalg.inv( q ) @ q_new )),
      "\nse3_vee(logm(np.linalg.inv( q ) @ q_new )) is\n", se3_vee(logm( np.linalg.inv( q_mnf.transform() ) @ q_new_mnf.transform() )),
      "\nmanifse32se3( q_new_mnf - q_mnf ) is\n", manifse32se3( q_new_mnf - q_mnf ))


q_new is 
 [[ 0.08459653  0.88833524  0.45133572  0.94126826]
 [ 0.9449502   0.07216584 -0.31915702  0.80441615]
 [-0.31608945  0.45348936 -0.83332758  0.70183957]
 [ 0.          0.          0.          1.        ]] 
q is 
 [[ 0.4666685  -0.76000163  0.45234724  0.52049747]
 [-0.45036899 -0.64438034 -0.61801436  0.02507073]
 [ 0.76117559  0.08468466 -0.64299318  0.33544752]
 [ 0.          0.          0.          1.        ]]
q_new_mnf is 
 [[ 0.08459653  0.88833524  0.45133572  0.94126826]
 [ 0.9449502   0.07216584 -0.31915702  0.80441615]
 [-0.31608945  0.45348936 -0.83332758  0.70183957]
 [ 0.          0.          0.          1.        ]] 
q_mnf is 
 [[ 0.4666685  -0.76000163  0.45234724  0.52049747]
 [-0.45036899 -0.64438034 -0.61801436  0.02507073]
 [ 0.76117559  0.08468466 -0.64299318  0.33544752]
 [ 0.          0.          0.          1.        ]]
se3_vee(logm(np.linalg.inv( q ) @ q_new )) is
 [ 0.43771647  0.10005804 -2.2835324   1.03924482 -0.35952824 -0.33260726] 
se3_vee(logm

In [57]:
%%timeit
se3_vee(logm(np.linalg.inv( q ) @ q_new ))

2.94 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [55]:
%%timeit
# q_new_mnf = SE32manifSE3(q_new)
# q_mnf = SE32manifSE3(q)
manifse32se3( q_new_mnf - q_mnf )

4.46 µs ± 295 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
from scipy.linalg import expm

X = SE3.Random().transform()
print(X)


[[ 0.72553685  0.55032358 -0.41320726 -0.19811121]
 [-0.16755739  0.72362729  0.66954318 -0.74041911]
 [ 0.66747345 -0.41654232  0.61722904 -0.7823824 ]
 [ 0.          0.          0.          1.        ]]
[[ 1.78441935  1.19254358 -0.38238142 -0.69712937]
 [ 0.10982063  1.77792206  1.24944678 -2.23628007]
 [ 1.24752362 -0.38860988  1.4159014  -1.55015766]
 [ 0.          0.          0.          2.71828183]]
