In [12]:
from manifpy import SE3, SE3Tangent
import numpy as np

X = SE3.Identity()
print(X)
Xbar = SE3.Identity()
print(Xbar)
J_err_Xt = np.zeros((SE3.DoF, SE3.DoF))

X.minus( Xbar, J_err_Xt )

J_err_Xt

0 0 0 0 0 0 1
0 0 0 0 0 0 1


array([[ 1.,  0.,  0., -0., -0., -0.],
       [ 0.,  1.,  0., -0., -0., -0.],
       [ 0.,  0.,  1., -0., -0., -0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [18]:
X = SE3.Identity()

print(X.coeffs())
print(X.quat())
print(X.x())
print(X.y())
print(X.z())

[0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 1.]
0.0
0.0
0.0


In [2]:
import numpy as jnp
import numpy as np

jnp.array([3])

array([3])

In [23]:
print(X + SE3Tangent(np.array([1.,1.,1.,0.,0.,0.])))

1 1 1 0 0 0 1
